language: bash
services:
  - docker
sudo: required
addons:
  apt:
    packages:
      - docker-ce
script:
  - ./travis.sh
after_success:
  - docker images
branches:
  only:
    - master
  except:
    - /^*-v[0-9]/
    - /^v\d.*$/
